// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Bot$Record = require("../src/Bot.bs.js");

Bot$Record.bot(/* record */Block.record(["token"], ["<Your token here>"])).then((function (bot) {
          console.log(bot);
          return Promise.resolve(/* () */0);
        })).catch((function (error) {
        console.log(error);
        return Promise.resolve(/* () */0);
      }));

function hang(param) {
  setTimeout(hang, 50000);
  return /* () */0;
}

exports.hang = hang;
/*  Not a pure module */
