// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';


function bot(settings) {
  return new Promise((function (resolve, reject) {
                return resolve(/* record */[/* token */settings[/* token */0]]);
              }));
}

exports.bot = bot;
/* No side effect */
