// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var IsomorphicWs = require("isomorphic-ws");

function bot(settings) {
  return new Promise((function (resolve, reject) {
                var ws = new IsomorphicWs("wss://gateway.discord.gg/?v=6&encoding=json");
                ws.on("open", (function (param) {
                        console.log("Opened");
                        return /* () */0;
                      }));
                return resolve(/* record */[
                            /* settings */settings,
                            /* ws */ws
                          ]);
              }));
}

exports.bot = bot;
/* isomorphic-ws Not a pure module */
