// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_module = require("bs-platform/lib/js/caml_module.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");
var Json_encode = require("@glennsl/bs-json/lib/js/src/Json_encode.bs.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var $$Permissions = /* module */Block.localModule([], []);

var User = /* module */Block.localModule([], []);

var Presence = /* module */Block.localModule([], []);

var Channel = /* module */Block.localModule([], []);

var Emoji = /* module */Block.localModule([], []);

var Message = /* module */Block.localModule([], []);

var UnknownMessage = Caml_exceptions.create("Data-Record.UnknownMessage");

function op_of_payload(payload) {
  if (typeof payload === "number") {
    if (payload === 0) {
      return 7;
    } else {
      return 11;
    }
  } else {
    switch (payload.tag | 0) {
      case 0 : 
          return 0;
      case 1 : 
          return 1;
      case 2 : 
          return 2;
      case 3 : 
          return 3;
      case 4 : 
          return 4;
      case 5 : 
          return 6;
      case 6 : 
      case 7 : 
          return 8;
      case 8 : 
          return 9;
      case 9 : 
          return 10;
      
    }
  }
}

function t_of_payload(payload) {
  if (typeof payload === "number" || payload.tag) {
    return /* Missing */0;
  } else {
    var tmp;
    switch (payload[0].tag | 0) {
      case 0 : 
          tmp = "READY";
          break;
      case 1 : 
          tmp = "RESUMED";
          break;
      case 2 : 
          tmp = "CHANNEL_CREATE";
          break;
      case 3 : 
          tmp = "CHANNEL_UPDATE";
          break;
      case 4 : 
          tmp = "CHANNEL_DELETE";
          break;
      case 5 : 
          tmp = "CHANNEL_PINS_UPDATE";
          break;
      case 6 : 
          tmp = "GUILD_CREATE";
          break;
      case 7 : 
          tmp = "MESSAGE_CREATE";
          break;
      case 8 : 
          tmp = "MESSAGE_UPDATE";
          break;
      case 9 : 
          tmp = "MESSAGE_DELETE";
          break;
      case 10 : 
          tmp = "MESSAGE_DELETE_BULK";
          break;
      case 11 : 
          tmp = "MESSAGE_REACTION_ADD";
          break;
      case 12 : 
          tmp = "MESSAGE_REACTION_REMOVE";
          break;
      case 13 : 
          tmp = "MESSAGE_REACTION_REMOVE_ALL";
          break;
      case 14 : 
          tmp = "TYPING_START";
          break;
      
    }
    return /* Field */Block.simpleVariant("Field", [tmp]);
  }
}

function optionalField(key, decoder, json) {
  var match = Json_decode.optional((function (param) {
          return Json_decode.field(key, decoder, param);
        }), json);
  if (match !== undefined) {
    return /* Field */Block.simpleVariant("Field", [Caml_option.valFromOption(match)]);
  } else {
    return /* Missing */0;
  }
}

function role(json) {
  return /* record */Block.record([
            "id",
            "name",
            "color",
            "hoist",
            "position",
            "permissions",
            "managed",
            "mentionable"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("name", Json_decode.string, json),
            Json_decode.field("color", Json_decode.$$int, json),
            Json_decode.field("hoist", Json_decode.bool, json),
            Json_decode.field("position", Json_decode.$$int, json),
            Json_decode.field("permissions", Json_decode.$$int, json),
            Json_decode.field("managed", Json_decode.bool, json),
            Json_decode.field("mentionable", Json_decode.bool, json)
          ]);
}

var $$Permissions$1 = /* module */Block.localModule(["role"], [role]);

function t(json) {
  return /* record */Block.record([
            "id",
            "username",
            "discriminator",
            "avatar",
            "bot",
            "mfaEnabled",
            "locale",
            "verified",
            "email",
            "flags",
            "premiumType"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("username", Json_decode.string, json),
            Json_decode.field("discriminator", Json_decode.string, json),
            Json_decode.field("avatar", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("bot", Json_decode.bool, json),
            optionalField("mfa_enabled", Json_decode.bool, json),
            optionalField("locale", Json_decode.string, json),
            optionalField("verified", Json_decode.bool, json),
            optionalField("email", Json_decode.string, json),
            optionalField("flags", Json_decode.$$int, json),
            optionalField("premium_type", Json_decode.$$int, json)
          ]);
}

var User$1 = /* module */Block.localModule(["t"], [t]);

function timestamps(json) {
  return /* record */Block.record([
            "start",
            "end_"
          ], [
            optionalField("start", Json_decode.$$int, json),
            optionalField("end", Json_decode.$$int, json)
          ]);
}

function party(json) {
  return /* record */Block.record([
            "id",
            "size"
          ], [
            optionalField("id", Json_decode.string, json),
            optionalField("size", (function (param) {
                    return Json_decode.array(Json_decode.$$int, param);
                  }), json)
          ]);
}

function assets(json) {
  return /* record */Block.record([
            "largeImage",
            "largeText",
            "smallImage",
            "smallText"
          ], [
            optionalField("large_image", Json_decode.string, json),
            optionalField("large_text", Json_decode.string, json),
            optionalField("small_image", Json_decode.string, json),
            optionalField("small_text", Json_decode.string, json)
          ]);
}

function secrets(json) {
  return /* record */Block.record([
            "join",
            "spectate",
            "match"
          ], [
            optionalField("join", Json_decode.string, json),
            optionalField("spectate", Json_decode.string, json),
            optionalField("match", Json_decode.string, json)
          ]);
}

function activity(json) {
  return /* record */Block.record([
            "name",
            "type_",
            "url",
            "timestamps",
            "applicationId",
            "details",
            "state",
            "party",
            "assets",
            "secrets",
            "instance",
            "flags"
          ], [
            Json_decode.field("name", Json_decode.string, json),
            Json_decode.field("type", Json_decode.$$int, json),
            optionalField("url", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("timestamps", timestamps, json),
            optionalField("application_id", Json_decode.string, json),
            optionalField("details", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("state", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("party", party, json),
            optionalField("assets", assets, json),
            optionalField("secrets", secrets, json),
            optionalField("instance", Json_decode.bool, json),
            optionalField("flags", Json_decode.$$int, json)
          ]);
}

function clientStatus(json) {
  return /* record */Block.record([
            "desktop",
            "mobile",
            "web"
          ], [
            optionalField("desktop", Json_decode.string, json),
            optionalField("mobile", Json_decode.string, json),
            optionalField("web", Json_decode.string, json)
          ]);
}

function update(json) {
  return /* record */Block.record([
            "user",
            "roles",
            "game",
            "guildId",
            "status",
            "activities",
            "clientStatus"
          ], [
            Json_decode.field("user", t, json),
            Json_decode.field("roles", (function (param) {
                    return Json_decode.array(Json_decode.string, param);
                  }), json),
            Json_decode.field("game", (function (param) {
                    return Json_decode.optional(activity, param);
                  }), json),
            Json_decode.field("guild_id", Json_decode.string, json),
            Json_decode.field("status", Json_decode.string, json),
            Json_decode.field("activities", (function (param) {
                    return Json_decode.array(activity, param);
                  }), json),
            Json_decode.field("client_status", clientStatus, json)
          ]);
}

var Presence$1 = /* module */Block.localModule([
    "timestamps",
    "party",
    "assets",
    "secrets",
    "activity",
    "clientStatus",
    "update"
  ], [
    timestamps,
    party,
    assets,
    secrets,
    activity,
    clientStatus,
    update
  ]);

function overwrite(json) {
  return /* record */Block.record([
            "id",
            "type_",
            "allow",
            "deny"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("type", Json_decode.string, json),
            Json_decode.field("allow", Json_decode.$$int, json),
            Json_decode.field("deny", Json_decode.$$int, json)
          ]);
}

function t$1(json) {
  return /* record */Block.record([
            "id",
            "type_",
            "guildId",
            "position",
            "permissionOverwrites",
            "name",
            "topic",
            "nsfw",
            "lastMessageId",
            "bitrate",
            "userLimit",
            "rateLimitPerUser",
            "recipients",
            "icon",
            "ownerId",
            "applicationId",
            "parentId",
            "lastPinTimestamp"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("type", Json_decode.$$int, json),
            optionalField("guild_id", Json_decode.string, json),
            optionalField("position", Json_decode.$$int, json),
            optionalField("permission_overwrites", (function (param) {
                    return Json_decode.array(overwrite, param);
                  }), json),
            optionalField("name", Json_decode.string, json),
            optionalField("topic", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("nsfw", Json_decode.bool, json),
            optionalField("last_message_id", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("bitrate", Json_decode.$$int, json),
            optionalField("user_limit", Json_decode.$$int, json),
            optionalField("rate_limit_per_user", Json_decode.$$int, json),
            optionalField("recipients", (function (param) {
                    return Json_decode.array(t, param);
                  }), json),
            optionalField("icon", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("owner_id", Json_decode.string, json),
            optionalField("application_id", Json_decode.string, json),
            optionalField("parent_id", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("last_pin_timestamp", Json_decode.date, json)
          ]);
}

function pinsUpdate(json) {
  return /* record */Block.record([
            "channelId",
            "lastPinTimestamp"
          ], [
            Json_decode.field("channel_id", Json_decode.string, json),
            optionalField("last_pin_timestamp", Json_decode.date, json)
          ]);
}

var Channel$1 = /* module */Block.localModule([
    "overwrite",
    "t",
    "create",
    "update",
    "delete",
    "pinsUpdate"
  ], [
    overwrite,
    t$1,
    t$1,
    t$1,
    t$1,
    pinsUpdate
  ]);

function t$2(json) {
  return /* record */Block.record([
            "id",
            "name",
            "roles",
            "user",
            "requireColons",
            "managed",
            "animated"
          ], [
            Json_decode.field("id", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            Json_decode.field("name", Json_decode.string, json),
            optionalField("roles", (function (param) {
                    return Json_decode.array(Json_decode.string, param);
                  }), json),
            optionalField("user", t, json),
            optionalField("require_colons", Json_decode.bool, json),
            optionalField("managed", Json_decode.bool, json),
            optionalField("animated", Json_decode.bool, json)
          ]);
}

var Emoji$1 = /* module */Block.localModule(["t"], [t$2]);

var Voice_ = Caml_module.init_mod([
      "Data.re",
      740,
      62
    ], [[0]]);

var Guild_ = Caml_module.init_mod([
      "Data.re",
      756,
      6
    ], [[
        0,
        0,
        0,
        0
      ]]);

function state(json) {
  return /* record */Block.record([
            "guildId",
            "channelId",
            "userId",
            "member"
          ], [
            Json_decode.field("guild_id", Json_decode.string, json),
            Json_decode.field("channel_id", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            Json_decode.field("user_id", Json_decode.string, json),
            optionalField("member", Guild_[/* member */0], json)
          ]);
}

Caml_module.update_mod([[0]], Voice_, /* module */Block.localModule(["state"], [state]));

function member(json) {
  return /* record */Block.record([
            "user",
            "nick",
            "roles",
            "joinedAt",
            "deaf",
            "mute"
          ], [
            Json_decode.field("user", t, json),
            optionalField("nick", Json_decode.string, json),
            Json_decode.field("roles", (function (param) {
                    return Json_decode.array(Json_decode.string, param);
                  }), json),
            Json_decode.field("joined_at", Json_decode.date, json),
            Json_decode.field("deaf", Json_decode.bool, json),
            Json_decode.field("mute", Json_decode.bool, json)
          ]);
}

function unavailable(json) {
  return /* record */Block.record([
            "id",
            "unavailable"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("unavailable", Json_decode.bool, json)
          ]);
}

function t$3(json) {
  var partial_arg = Voice_[/* state */0];
  return /* record */Block.record([
            "id",
            "name",
            "icon",
            "splash",
            "owner",
            "ownerId",
            "permissions",
            "region",
            "afkChannelId",
            "afkTimeout",
            "embedEnabled",
            "embedChannelId",
            "verificationLevel",
            "defaultMessageNotifications",
            "explicitContentFilter",
            "roles",
            "emojis",
            "features",
            "mfaLevel",
            "applicationId",
            "widgetEnabled",
            "widgetChannelId",
            "systemChannelId",
            "joinedAt",
            "large",
            "unavailable",
            "memberCount",
            "voiceStates",
            "members",
            "channels",
            "presences",
            "maxPresences",
            "maxMembers",
            "vanityUrlCode",
            "description",
            "banner"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("name", Json_decode.string, json),
            Json_decode.field("icon", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            Json_decode.field("splash", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("owner", Json_decode.bool, json),
            Json_decode.field("owner_id", Json_decode.string, json),
            optionalField("permissions", Json_decode.$$int, json),
            Json_decode.field("region", Json_decode.string, json),
            Json_decode.field("afk_channel_id", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            Json_decode.field("afk_timeout", Json_decode.$$int, json),
            optionalField("embed_enabled", Json_decode.bool, json),
            optionalField("embed_channel_id", Json_decode.string, json),
            Json_decode.field("verification_level", Json_decode.$$int, json),
            Json_decode.field("default_message_notifications", Json_decode.$$int, json),
            Json_decode.field("explicit_content_filter", Json_decode.$$int, json),
            Json_decode.field("roles", (function (param) {
                    return Json_decode.array(role, param);
                  }), json),
            Json_decode.field("emojis", (function (param) {
                    return Json_decode.array(t$2, param);
                  }), json),
            Json_decode.field("features", (function (param) {
                    return Json_decode.array(Json_decode.string, param);
                  }), json),
            Json_decode.field("mfa_level", Json_decode.$$int, json),
            Json_decode.field("application_id", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("widget_enabled", Json_decode.bool, json),
            optionalField("widget_channel_id", Json_decode.string, json),
            Json_decode.field("system_channel_id", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            optionalField("joined_at", Json_decode.date, json),
            optionalField("large", Json_decode.bool, json),
            optionalField("unavailable", Json_decode.bool, json),
            optionalField("member_count", Json_decode.$$int, json),
            optionalField("voice_states", (function (param) {
                    return Json_decode.array(partial_arg, param);
                  }), json),
            optionalField("members", (function (param) {
                    return Json_decode.array(member, param);
                  }), json),
            optionalField("channels", (function (param) {
                    return Json_decode.array(t$1, param);
                  }), json),
            optionalField("presences", (function (param) {
                    return Json_decode.array(update, param);
                  }), json),
            optionalField("max_presences", (function (param) {
                    return Json_decode.optional(Json_decode.$$int, param);
                  }), json),
            optionalField("max_members", Json_decode.$$int, json),
            Json_decode.field("vanity_url_code", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            Json_decode.field("description", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            Json_decode.field("banner", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json)
          ]);
}

Caml_module.update_mod([[
        0,
        0,
        0,
        0
      ]], Guild_, /* module */Block.localModule([
        "member",
        "unavailable",
        "t",
        "create"
      ], [
        member,
        unavailable,
        t$3,
        t$3
      ]));

function attachment(json) {
  return /* record */Block.record([
            "id",
            "filename",
            "size",
            "url",
            "proxyUrl",
            "height",
            "width"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("filename", Json_decode.string, json),
            Json_decode.field("size", Json_decode.$$int, json),
            Json_decode.field("url", Json_decode.string, json),
            Json_decode.field("proxy_url", Json_decode.string, json),
            Json_decode.field("height", (function (param) {
                    return Json_decode.optional(Json_decode.$$int, param);
                  }), json),
            Json_decode.field("width", (function (param) {
                    return Json_decode.optional(Json_decode.$$int, param);
                  }), json)
          ]);
}

function embedFooter(json) {
  return /* record */Block.record([
            "text",
            "iconUrl",
            "proxyIconUrl"
          ], [
            Json_decode.field("text", Json_decode.string, json),
            optionalField("icon_url", Json_decode.string, json),
            optionalField("proxy_icon_url", Json_decode.string, json)
          ]);
}

function embedImage(json) {
  return /* record */Block.record([
            "url",
            "proxyUrl",
            "height",
            "width"
          ], [
            optionalField("url", Json_decode.string, json),
            optionalField("proxy_url", Json_decode.string, json),
            optionalField("height", Json_decode.$$int, json),
            optionalField("width", Json_decode.$$int, json)
          ]);
}

function embedThumbnail(json) {
  return /* record */Block.record([
            "url",
            "proxyUrl",
            "height",
            "width"
          ], [
            optionalField("url", Json_decode.string, json),
            optionalField("proxy_url", Json_decode.string, json),
            optionalField("height", Json_decode.$$int, json),
            optionalField("width", Json_decode.$$int, json)
          ]);
}

function embedVideo(json) {
  return /* record */Block.record([
            "url",
            "height",
            "width"
          ], [
            optionalField("url", Json_decode.string, json),
            optionalField("height", Json_decode.$$int, json),
            optionalField("width", Json_decode.$$int, json)
          ]);
}

function embedProvider(json) {
  return /* record */Block.record([
            "name",
            "url"
          ], [
            optionalField("name", Json_decode.string, json),
            optionalField("url", Json_decode.string, json)
          ]);
}

function embedAuthor(json) {
  return /* record */Block.record([
            "name",
            "url",
            "iconUrl",
            "proxyIconUrl"
          ], [
            optionalField("name", Json_decode.string, json),
            optionalField("url", Json_decode.string, json),
            optionalField("icon_url", Json_decode.string, json),
            optionalField("proxy_icon_url", Json_decode.string, json)
          ]);
}

function embedField(json) {
  return /* record */Block.record([
            "name",
            "value",
            "inline"
          ], [
            Json_decode.field("name", Json_decode.string, json),
            Json_decode.field("value", Json_decode.string, json),
            optionalField("inline", Json_decode.bool, json)
          ]);
}

function embed(json) {
  return /* record */Block.record([
            "title",
            "type_",
            "description",
            "url",
            "timestamp",
            "color",
            "footer",
            "image",
            "thumbnail",
            "video",
            "provider",
            "author",
            "field"
          ], [
            optionalField("title", Json_decode.string, json),
            optionalField("type", Json_decode.string, json),
            optionalField("description", Json_decode.string, json),
            optionalField("url", Json_decode.string, json),
            optionalField("timestamp", Json_decode.date, json),
            optionalField("color", Json_decode.$$int, json),
            optionalField("footer", embedFooter, json),
            optionalField("image", embedImage, json),
            optionalField("thumbnail", embedThumbnail, json),
            optionalField("video", embedVideo, json),
            optionalField("provider", embedProvider, json),
            optionalField("author", embedAuthor, json),
            optionalField("field", (function (param) {
                    return Json_decode.array(embedField, param);
                  }), json)
          ]);
}

function reaction(json) {
  return /* record */Block.record([
            "count",
            "me",
            "emoji"
          ], [
            Json_decode.field("count", Json_decode.$$int, json),
            Json_decode.field("me", Json_decode.bool, json),
            Json_decode.field("emoji", t$2, json)
          ]);
}

function activity$1(json) {
  return /* record */Block.record([
            "type_",
            "partyId"
          ], [
            Json_decode.field("type", Json_decode.$$int, json),
            optionalField("party_id", Json_decode.string, json)
          ]);
}

function application(json) {
  return /* record */Block.record([
            "id",
            "coverImage",
            "description",
            "icon",
            "name"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            optionalField("cover_image", Json_decode.string, json),
            Json_decode.field("description", Json_decode.string, json),
            Json_decode.field("icon", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            Json_decode.field("name", Json_decode.string, json)
          ]);
}

function t$4(json) {
  return /* record */Block.record([
            "id",
            "channelId",
            "guildId",
            "author",
            "member",
            "content",
            "timestamp",
            "editedTimestamp",
            "tts",
            "mentionEveryone",
            "mentions",
            "mentionRoles",
            "attachments",
            "embeds",
            "reactions",
            "nonce",
            "pinned",
            "webhookId",
            "type_",
            "activity",
            "application"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("channel_id", Json_decode.string, json),
            optionalField("guild_id", Json_decode.string, json),
            Json_decode.field("author", t, json),
            optionalField("member", Guild_[/* member */0], json),
            Json_decode.field("content", Json_decode.string, json),
            Json_decode.field("timestamp", Json_decode.date, json),
            Json_decode.field("edited_timestamp", (function (param) {
                    return Json_decode.optional(Json_decode.date, param);
                  }), json),
            Json_decode.field("tts", Json_decode.bool, json),
            Json_decode.field("mention_everyone", Json_decode.bool, json),
            Json_decode.field("mentions", (function (param) {
                    return Json_decode.array(t, param);
                  }), json),
            Json_decode.field("mention_roles", (function (param) {
                    return Json_decode.array(Json_decode.string, param);
                  }), json),
            Json_decode.field("attachments", (function (param) {
                    return Json_decode.array(attachment, param);
                  }), json),
            Json_decode.field("embeds", (function (param) {
                    return Json_decode.array(embed, param);
                  }), json),
            optionalField("reactions", (function (param) {
                    return Json_decode.array(reaction, param);
                  }), json),
            optionalField("nonce", (function (param) {
                    return Json_decode.optional(Json_decode.string, param);
                  }), json),
            Json_decode.field("pinned", Json_decode.bool, json),
            optionalField("webhook_id", Json_decode.string, json),
            Json_decode.field("type", Json_decode.$$int, json),
            optionalField("activity", activity$1, json),
            optionalField("application", application, json)
          ]);
}

function $$delete(json) {
  return /* record */Block.record([
            "id",
            "channelId",
            "guildId"
          ], [
            Json_decode.field("id", Json_decode.string, json),
            Json_decode.field("channel_id", Json_decode.string, json),
            Json_decode.field("guild_id", Json_decode.string, json)
          ]);
}

function deleteBulk(json) {
  return /* record */Block.record([
            "ids",
            "channelId",
            "guildId"
          ], [
            Json_decode.field("ids", (function (param) {
                    return Json_decode.array(Json_decode.string, param);
                  }), json),
            Json_decode.field("channel_id", Json_decode.string, json),
            Json_decode.field("guild_id", Json_decode.string, json)
          ]);
}

function reactionAdd(json) {
  return /* record */Block.record([
            "userId",
            "channelId",
            "messageId",
            "guildId",
            "emoji"
          ], [
            Json_decode.field("user_id", Json_decode.string, json),
            Json_decode.field("channel_id", Json_decode.string, json),
            Json_decode.field("message_id", Json_decode.string, json),
            optionalField("guild_id", Json_decode.string, json),
            Json_decode.field("emoji", t$2, json)
          ]);
}

function reactionRemove(json) {
  return /* record */Block.record([
            "userId",
            "channelId",
            "messageId",
            "guildId",
            "emoji"
          ], [
            Json_decode.field("user_id", Json_decode.string, json),
            Json_decode.field("channel_id", Json_decode.string, json),
            Json_decode.field("message_id", Json_decode.string, json),
            optionalField("guild_id", Json_decode.string, json),
            Json_decode.field("emoji", t$2, json)
          ]);
}

function reactionRemoveAll(json) {
  return /* record */Block.record([
            "channelId",
            "messageId",
            "guildId"
          ], [
            Json_decode.field("channel_id", Json_decode.string, json),
            Json_decode.field("message_id", Json_decode.string, json),
            optionalField("guild_id", Json_decode.string, json)
          ]);
}

var Message$1 = /* module */Block.localModule([
    "attachment",
    "embedFooter",
    "embedImage",
    "embedThumbnail",
    "embedVideo",
    "embedProvider",
    "embedAuthor",
    "embedField",
    "embed",
    "reaction",
    "activity",
    "application",
    "t",
    "create",
    "update",
    "delete",
    "deleteBulk",
    "reactionAdd",
    "reactionRemove",
    "reactionRemoveAll"
  ], [
    attachment,
    embedFooter,
    embedImage,
    embedThumbnail,
    embedVideo,
    embedProvider,
    embedAuthor,
    embedField,
    embed,
    reaction,
    activity$1,
    application,
    t$4,
    t$4,
    t$4,
    $$delete,
    deleteBulk,
    reactionAdd,
    reactionRemove,
    reactionRemoveAll
  ]);

function ready(json) {
  var partial_arg = Guild_[/* unavailable */1];
  return /* record */Block.record([
            "v",
            "user",
            "privateChannels",
            "guilds",
            "sessionId",
            "trace",
            "shard"
          ], [
            Json_decode.field("v", Json_decode.$$int, json),
            Json_decode.field("user", t, json),
            Json_decode.field("private_channels", (function (param) {
                    return Json_decode.array((function (param) {
                                  return /* () */0;
                                }), param);
                  }), json),
            Json_decode.field("guilds", (function (param) {
                    return Json_decode.array(partial_arg, param);
                  }), json),
            Json_decode.field("session_id", Json_decode.string, json),
            Json_decode.field("_trace", (function (param) {
                    return Json_decode.array(Json_decode.string, param);
                  }), json),
            optionalField("shard", (function (param) {
                    return Json_decode.array(Json_decode.$$int, param);
                  }), json)
          ]);
}

function resumed(json) {
  return /* record */Block.record(["trace"], [Json_decode.field("_trace", (function (param) {
                    return Json_decode.array(Json_decode.string, param);
                  }), json)]);
}

function typingStart(json) {
  return /* record */Block.record([
            "channelId",
            "guildId",
            "userId",
            "timestamp"
          ], [
            Json_decode.field("channel_id", Json_decode.string, json),
            optionalField("guild_id", Json_decode.string, json),
            Json_decode.field("user_id", Json_decode.string, json),
            Json_decode.field("timestamp", Json_decode.$$int, json)
          ]);
}

function hello(json) {
  return /* record */Block.record([
            "heartbeatInterval",
            "trace"
          ], [
            Json_decode.field("heartbeat_interval", Json_decode.$$int, json),
            Json_decode.field("_trace", (function (param) {
                    return Json_decode.array(Json_decode.string, param);
                  }), json)
          ]);
}

function data(json) {
  return /* record */Block.record([
            "op",
            "d",
            "s",
            "t"
          ], [
            Json_decode.field("op", Json_decode.$$int, json),
            Json_decode.field("d", (function (j) {
                    var match = Json_decode.field("op", Json_decode.$$int, json);
                    switch (match) {
                      case 0 : 
                          var match$1 = Json_decode.field("t", Json_decode.string, json);
                          var tmp;
                          switch (match$1) {
                            case "CHANNEL_CREATE" : 
                                tmp = /* ChannelCreate */Block.variant("ChannelCreate", 2, [t$1(j)]);
                                break;
                            case "CHANNEL_DELETE" : 
                                tmp = /* ChannelDelete */Block.variant("ChannelDelete", 4, [t$1(j)]);
                                break;
                            case "CHANNEL_PINS_UPDATE" : 
                                tmp = /* ChannelPinsUpdate */Block.variant("ChannelPinsUpdate", 5, [pinsUpdate(j)]);
                                break;
                            case "CHANNEL_UPDATE" : 
                                tmp = /* ChannelUpdate */Block.variant("ChannelUpdate", 3, [t$1(j)]);
                                break;
                            case "GUILD_CREATE" : 
                                tmp = /* GuildCreate */Block.variant("GuildCreate", 6, [Curry._1(Guild_[/* create */3], j)]);
                                break;
                            case "MESSAGE_CREATE" : 
                                tmp = /* MessageCreate */Block.variant("MessageCreate", 7, [t$4(j)]);
                                break;
                            case "MESSAGE_DELETE" : 
                                tmp = /* MessageDelete */Block.variant("MessageDelete", 9, [$$delete(j)]);
                                break;
                            case "MESSAGE_DELETE_BULK" : 
                                tmp = /* MessageDeleteBulk */Block.variant("MessageDeleteBulk", 10, [deleteBulk(j)]);
                                break;
                            case "MESSAGE_REACTION_ADD" : 
                                tmp = /* MessageReactionAdd */Block.variant("MessageReactionAdd", 11, [reactionAdd(j)]);
                                break;
                            case "MESSAGE_REACTION_REMOVE" : 
                                tmp = /* MessageReactionRemove */Block.variant("MessageReactionRemove", 12, [reactionRemove(j)]);
                                break;
                            case "MESSAGE_REACTION_REMOVE_ALL" : 
                                tmp = /* MessageReactionRemoveAll */Block.variant("MessageReactionRemoveAll", 13, [reactionRemoveAll(j)]);
                                break;
                            case "MESSAGE_UPDATE" : 
                                tmp = /* MessageUpdate */Block.variant("MessageUpdate", 8, [t$4(j)]);
                                break;
                            case "READY" : 
                                tmp = /* Ready */Block.variant("Ready", 0, [ready(j)]);
                                break;
                            case "RESUMED" : 
                                tmp = /* Resumed */Block.variant("Resumed", 1, [resumed(j)]);
                                break;
                            case "TYPING_START" : 
                                tmp = /* TypingStart */Block.variant("TypingStart", 14, [typingStart(j)]);
                                break;
                            default:
                              throw [
                                    UnknownMessage,
                                    json
                                  ];
                          }
                          return /* Dispatch */Block.variant("Dispatch", 0, [tmp]);
                      case 7 : 
                          return /* Reconnect */0;
                      case 1 : 
                      case 2 : 
                      case 3 : 
                      case 4 : 
                      case 5 : 
                      case 6 : 
                      case 8 : 
                          throw [
                                UnknownMessage,
                                json
                              ];
                      case 9 : 
                          return /* InvalidSession */Block.variant("InvalidSession", 8, [Json_decode.bool(j)]);
                      case 10 : 
                          return /* Hello */Block.variant("Hello", 9, [hello(j)]);
                      case 11 : 
                          return /* Ack */1;
                      default:
                        throw [
                              UnknownMessage,
                              json
                            ];
                    }
                  }), json),
            optionalField("s", Json_decode.$$int, json),
            optionalField("t", Json_decode.string, json)
          ]);
}

var Decode = /* module */Block.localModule([
    "optionalField",
    "Permissions",
    "User",
    "Presence",
    "Channel",
    "Emoji",
    "Voice_",
    "Guild_",
    "Voice",
    "Guild",
    "Message",
    "ready",
    "resumed",
    "typingStart",
    "hello",
    "data"
  ], [
    optionalField,
    $$Permissions$1,
    User$1,
    Presence$1,
    Channel$1,
    Emoji$1,
    Voice_,
    Guild_,
    0,
    0,
    Message$1,
    ready,
    resumed,
    typingStart,
    hello,
    data
  ]);

function required(encoder, r) {
  return /* Field */Block.simpleVariant("Field", [Curry._1(encoder, r)]);
}

function optional(encoder, r) {
  if (r) {
    return /* Field */Block.simpleVariant("Field", [Curry._1(encoder, r[0])]);
  } else {
    return /* Missing */0;
  }
}

function nullOpt(encoder, r) {
  if (r !== undefined) {
    return Curry._1(encoder, Caml_option.valFromOption(r));
  } else {
    return null;
  }
}

function objectOpt(fields) {
  return Json_encode.object_(List.fold_right((function (b, a) {
                    var match = b[1];
                    if (match) {
                      return /* :: */Block.simpleVariant("::", [
                                /* tuple */[
                                  b[0],
                                  match[0]
                                ],
                                a
                              ]);
                    } else {
                      return a;
                    }
                  }), fields, /* [] */0));
}

function timestamps$1(r) {
  return objectOpt(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "start",
                  optional((function (prim) {
                          return prim;
                        }), r[/* start */0])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "end",
                      optional((function (prim) {
                              return prim;
                            }), r[/* end_ */1])
                    ],
                    /* [] */0
                  ])
              ]));
}

function party$1(r) {
  return objectOpt(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "id",
                  optional((function (prim) {
                          return prim;
                        }), r[/* id */0])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "size",
                      optional((function (param) {
                              return Json_encode.array((function (prim) {
                                            return prim;
                                          }), param);
                            }), r[/* size */1])
                    ],
                    /* [] */0
                  ])
              ]));
}

function assets$1(r) {
  return objectOpt(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "large_image",
                  optional((function (prim) {
                          return prim;
                        }), r[/* largeImage */0])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "large_text",
                      optional((function (prim) {
                              return prim;
                            }), r[/* largeText */1])
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "small_image",
                          optional((function (prim) {
                                  return prim;
                                }), r[/* smallImage */2])
                        ],
                        /* :: */Block.simpleVariant("::", [
                            /* tuple */[
                              "small_text",
                              optional((function (prim) {
                                      return prim;
                                    }), r[/* smallText */3])
                            ],
                            /* [] */0
                          ])
                      ])
                  ])
              ]));
}

function secrets$1(r) {
  return objectOpt(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "join",
                  optional((function (prim) {
                          return prim;
                        }), r[/* join */0])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "spectate",
                      optional((function (prim) {
                              return prim;
                            }), r[/* spectate */1])
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "match",
                          optional((function (prim) {
                                  return prim;
                                }), r[/* match */2])
                        ],
                        /* [] */0
                      ])
                  ])
              ]));
}

function activity$2(r) {
  return objectOpt(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "name",
                  /* Field */Block.simpleVariant("Field", [r[/* name */0]])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "type",
                      /* Field */Block.simpleVariant("Field", [r[/* type_ */1]])
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "url",
                          optional((function (param) {
                                  return nullOpt((function (prim) {
                                                return prim;
                                              }), param);
                                }), r[/* url */2])
                        ],
                        /* :: */Block.simpleVariant("::", [
                            /* tuple */[
                              "timestamps",
                              optional(timestamps$1, r[/* timestamps */3])
                            ],
                            /* :: */Block.simpleVariant("::", [
                                /* tuple */[
                                  "application_id",
                                  optional((function (prim) {
                                          return prim;
                                        }), r[/* applicationId */4])
                                ],
                                /* :: */Block.simpleVariant("::", [
                                    /* tuple */[
                                      "details",
                                      optional((function (param) {
                                              return nullOpt((function (prim) {
                                                            return prim;
                                                          }), param);
                                            }), r[/* details */5])
                                    ],
                                    /* :: */Block.simpleVariant("::", [
                                        /* tuple */[
                                          "state",
                                          optional((function (param) {
                                                  return nullOpt((function (prim) {
                                                                return prim;
                                                              }), param);
                                                }), r[/* state */6])
                                        ],
                                        /* :: */Block.simpleVariant("::", [
                                            /* tuple */[
                                              "party",
                                              optional(party$1, r[/* party */7])
                                            ],
                                            /* :: */Block.simpleVariant("::", [
                                                /* tuple */[
                                                  "assets",
                                                  optional(assets$1, r[/* assets */8])
                                                ],
                                                /* :: */Block.simpleVariant("::", [
                                                    /* tuple */[
                                                      "secrets",
                                                      optional(secrets$1, r[/* secrets */9])
                                                    ],
                                                    /* :: */Block.simpleVariant("::", [
                                                        /* tuple */[
                                                          "instance",
                                                          optional((function (prim) {
                                                                  return prim;
                                                                }), r[/* instance */10])
                                                        ],
                                                        /* :: */Block.simpleVariant("::", [
                                                            /* tuple */[
                                                              "flags",
                                                              optional((function (prim) {
                                                                      return prim;
                                                                    }), r[/* flags */11])
                                                            ],
                                                            /* [] */0
                                                          ])
                                                      ])
                                                  ])
                                              ])
                                          ])
                                      ])
                                  ])
                              ])
                          ])
                      ])
                  ])
              ]));
}

var Presence$2 = /* module */Block.localModule([
    "timestamps",
    "party",
    "assets",
    "secrets",
    "activity"
  ], [
    timestamps$1,
    party$1,
    assets$1,
    secrets$1,
    activity$2
  ]);

function updateStatus(r) {
  return objectOpt(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "since",
                  /* Field */Block.simpleVariant("Field", [nullOpt((function (prim) {
                              return prim;
                            }), r[/* since */0])])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "game",
                      /* Field */Block.simpleVariant("Field", [nullOpt(activity$2, r[/* game */1])])
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "status",
                          /* Field */Block.simpleVariant("Field", [r[/* status */2]])
                        ],
                        /* :: */Block.simpleVariant("::", [
                            /* tuple */[
                              "afk",
                              /* Field */Block.simpleVariant("Field", [r[/* afk */3]])
                            ],
                            /* [] */0
                          ])
                      ])
                  ])
              ]));
}

function heartbeat(param) {
  return nullOpt((function (prim) {
                return prim;
              }), param);
}

function props(r) {
  return Json_encode.object_(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "$os",
                  r[/* os */0]
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "$browser",
                      r[/* browser */1]
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "$device",
                          r[/* device */2]
                        ],
                        /* [] */0
                      ])
                  ])
              ]));
}

function identify(r) {
  return objectOpt(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "token",
                  /* Field */Block.simpleVariant("Field", [r[/* token */0]])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "properties",
                      /* Field */Block.simpleVariant("Field", [props(r[/* properties */1])])
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "compress",
                          optional((function (prim) {
                                  return prim;
                                }), r[/* compress */2])
                        ],
                        /* :: */Block.simpleVariant("::", [
                            /* tuple */[
                              "large_threshold",
                              optional((function (prim) {
                                      return prim;
                                    }), r[/* largeThreshold */3])
                            ],
                            /* :: */Block.simpleVariant("::", [
                                /* tuple */[
                                  "shard",
                                  optional((function (param) {
                                          return Json_encode.array((function (prim) {
                                                        return prim;
                                                      }), param);
                                        }), r[/* shard */4])
                                ],
                                /* :: */Block.simpleVariant("::", [
                                    /* tuple */[
                                      "presence",
                                      optional(updateStatus, r[/* presence */5])
                                    ],
                                    /* [] */0
                                  ])
                              ])
                          ])
                      ])
                  ])
              ]));
}

function statusUpdate(r) {
  return Json_encode.object_(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "since",
                  nullOpt((function (prim) {
                          return prim;
                        }), r[/* since */0])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "game",
                      nullOpt(activity$2, r[/* game */1])
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "status",
                          r[/* status */2]
                        ],
                        /* :: */Block.simpleVariant("::", [
                            /* tuple */[
                              "afk",
                              r[/* afk */3]
                            ],
                            /* [] */0
                          ])
                      ])
                  ])
              ]));
}

function voiceStateUpdate(r) {
  return Json_encode.object_(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "guild_id",
                  r[/* guildId */0]
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "channel_id",
                      nullOpt((function (prim) {
                              return prim;
                            }), r[/* channelId */1])
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "self_mute",
                          r[/* selfMute */2]
                        ],
                        /* :: */Block.simpleVariant("::", [
                            /* tuple */[
                              "self_deaf",
                              r[/* selfDeaf */3]
                            ],
                            /* [] */0
                          ])
                      ])
                  ])
              ]));
}

function resume(r) {
  return Json_encode.object_(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "token",
                  r[/* token */0]
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "session_id",
                      r[/* sessionId */1]
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "seq",
                          r[/* seq */2]
                        ],
                        /* [] */0
                      ])
                  ])
              ]));
}

function requestGuildMembers(r) {
  return Json_encode.object_(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "guild_id",
                  r[/* guildId */0]
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "query",
                      r[/* query */1]
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "limit",
                          r[/* limit */2]
                        ],
                        /* [] */0
                      ])
                  ])
              ]));
}

function requestGuildMembersBulk(r) {
  return Json_encode.object_(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "guild_id",
                  Json_encode.array((function (prim) {
                          return prim;
                        }), r[/* guildId */0])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "query",
                      r[/* query */1]
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "limit",
                          r[/* limit */2]
                        ],
                        /* [] */0
                      ])
                  ])
              ]));
}

function data$1(r) {
  var match = r[/* d */1];
  var tmp;
  if (typeof match === "number") {
    tmp = /* Missing */0;
  } else {
    switch (match.tag | 0) {
      case 1 : 
          tmp = /* Field */Block.simpleVariant("Field", [nullOpt((function (prim) {
                      return prim;
                    }), match[0])]);
          break;
      case 2 : 
          tmp = /* Field */Block.simpleVariant("Field", [identify(match[0])]);
          break;
      case 3 : 
          tmp = /* Field */Block.simpleVariant("Field", [statusUpdate(match[0])]);
          break;
      case 4 : 
          tmp = /* Field */Block.simpleVariant("Field", [voiceStateUpdate(match[0])]);
          break;
      case 5 : 
          tmp = /* Field */Block.simpleVariant("Field", [resume(match[0])]);
          break;
      case 6 : 
          tmp = /* Field */Block.simpleVariant("Field", [requestGuildMembers(match[0])]);
          break;
      case 7 : 
          tmp = /* Field */Block.simpleVariant("Field", [requestGuildMembersBulk(match[0])]);
          break;
      default:
        tmp = /* Missing */0;
    }
  }
  return objectOpt(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "op",
                  /* Field */Block.simpleVariant("Field", [r[/* op */0]])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "d",
                      tmp
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "s",
                          optional((function (prim) {
                                  return prim;
                                }), r[/* s */2])
                        ],
                        /* :: */Block.simpleVariant("::", [
                            /* tuple */[
                              "t",
                              optional((function (prim) {
                                      return prim;
                                    }), r[/* t */3])
                            ],
                            /* [] */0
                          ])
                      ])
                  ])
              ]));
}

function dataFromPayload(r) {
  var r$1 = op_of_payload(r);
  var tmp;
  if (typeof r === "number") {
    tmp = /* Missing */0;
  } else {
    switch (r.tag | 0) {
      case 1 : 
          tmp = /* Field */Block.simpleVariant("Field", [nullOpt((function (prim) {
                      return prim;
                    }), r[0])]);
          break;
      case 2 : 
          tmp = /* Field */Block.simpleVariant("Field", [identify(r[0])]);
          break;
      case 3 : 
          tmp = /* Field */Block.simpleVariant("Field", [statusUpdate(r[0])]);
          break;
      case 4 : 
          tmp = /* Field */Block.simpleVariant("Field", [voiceStateUpdate(r[0])]);
          break;
      case 5 : 
          tmp = /* Field */Block.simpleVariant("Field", [resume(r[0])]);
          break;
      case 6 : 
          tmp = /* Field */Block.simpleVariant("Field", [requestGuildMembers(r[0])]);
          break;
      case 7 : 
          tmp = /* Field */Block.simpleVariant("Field", [requestGuildMembersBulk(r[0])]);
          break;
      default:
        tmp = /* Missing */0;
    }
  }
  return objectOpt(/* :: */Block.simpleVariant("::", [
                /* tuple */[
                  "op",
                  /* Field */Block.simpleVariant("Field", [r$1])
                ],
                /* :: */Block.simpleVariant("::", [
                    /* tuple */[
                      "d",
                      tmp
                    ],
                    /* :: */Block.simpleVariant("::", [
                        /* tuple */[
                          "t",
                          optional((function (prim) {
                                  return prim;
                                }), t_of_payload(r))
                        ],
                        /* [] */0
                      ])
                  ])
              ]));
}

var Encode = /* module */Block.localModule([
    "required",
    "optional",
    "nullOpt",
    "objectOpt",
    "Presence",
    "updateStatus",
    "heartbeat",
    "props",
    "identify",
    "statusUpdate",
    "voiceStateUpdate",
    "resume",
    "requestGuildMembers",
    "requestGuildMembersBulk",
    "data",
    "dataFromPayload"
  ], [
    required,
    optional,
    nullOpt,
    objectOpt,
    Presence$2,
    updateStatus,
    heartbeat,
    props,
    identify,
    statusUpdate,
    voiceStateUpdate,
    resume,
    requestGuildMembers,
    requestGuildMembersBulk,
    data$1,
    dataFromPayload
  ]);

var Voice = /* () */0;

var Guild = /* () */0;

exports.$$Permissions = $$Permissions;
exports.User = User;
exports.Presence = Presence;
exports.Channel = Channel;
exports.Emoji = Emoji;
exports.Voice = Voice;
exports.Guild = Guild;
exports.Message = Message;
exports.UnknownMessage = UnknownMessage;
exports.op_of_payload = op_of_payload;
exports.t_of_payload = t_of_payload;
exports.Decode = Decode;
exports.Encode = Encode;
/* Voice_ Not a pure module */
