// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Bot$Record = require("./Bot.bs.js");

Bot$Record.bot(/* record */[/* token */""]).then((function (bot) {
        console.log(bot);
        return Promise.resolve(bot);
      }));

/*  Not a pure module */
