// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Bot$Record = require("./Bot.bs.js");

Bot$Record.bot(/* record */Block.record(["token"], ["<your token here>"])).then((function (bot) {
        console.log(bot);
        return Promise.resolve(bot);
      }));

function hang(param) {
  setTimeout(hang, 50000);
  return /* () */0;
}

exports.hang = hang;
/*  Not a pure module */
