// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");

function getExn(param) {
  if (param) {
    return param[0];
  } else {
    return Js_exn.raiseError("getExn");
  }
}

function mapWithDefaultU(opt, $$default, f) {
  if (opt) {
    return f(opt[0]);
  } else {
    return $$default;
  }
}

function mapWithDefault(opt, $$default, f) {
  return mapWithDefaultU(opt, $$default, Curry.__1(f));
}

function mapU(opt, f) {
  if (opt) {
    return /* Field */Block.simpleVariant("Field", [f(opt[0])]);
  } else {
    return /* Missing */0;
  }
}

function map(opt, f) {
  return mapU(opt, Curry.__1(f));
}

function flatMapU(opt, f) {
  if (opt) {
    return f(opt[0]);
  } else {
    return /* Missing */0;
  }
}

function flatMap(opt, f) {
  return flatMapU(opt, Curry.__1(f));
}

function getWithDefault(opt, $$default) {
  if (opt) {
    return opt[0];
  } else {
    return $$default;
  }
}

function isField(param) {
  if (param) {
    return true;
  } else {
    return false;
  }
}

function isMissing(x) {
  return x === /* Missing */0;
}

function eqU(a, b, f) {
  if (a) {
    if (b) {
      return f(a[0], b[0]);
    } else {
      return false;
    }
  } else {
    return b === /* Missing */0;
  }
}

function eq(a, b, f) {
  return eqU(a, b, Curry.__2(f));
}

function cmpU(a, b, f) {
  if (a) {
    if (b) {
      return f(a[0], b[0]);
    } else {
      return 1;
    }
  } else if (b) {
    return -1;
  } else {
    return 0;
  }
}

function cmp(a, b, f) {
  return cmpU(a, b, Curry.__2(f));
}

exports.getExn = getExn;
exports.mapWithDefaultU = mapWithDefaultU;
exports.mapWithDefault = mapWithDefault;
exports.mapU = mapU;
exports.map = map;
exports.flatMapU = flatMapU;
exports.flatMap = flatMap;
exports.getWithDefault = getWithDefault;
exports.isField = isField;
exports.isMissing = isMissing;
exports.eqU = eqU;
exports.eq = eq;
exports.cmpU = cmpU;
exports.cmp = cmp;
/* No side effect */
